# Generated by Django 4.0.2 on 2022-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_price_currency_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
